### PR TITLE
Update GL translations (2021-07-02)

### PR DESCRIPTION
**Pull request by xurxodiz**
## ✅ Changes

- (docs) Gets Galician translation up to date

## 🌄 Context

Galician translation fell a bit behind the required strings. This fixes all of them.

## 🔒Checklist

- I tested my work on the feature environment

## 💅 Examples

fari_gl_screenshot

### CODE REVIEW

**Comment by xurxodiz** [comment]
Tangential question, but since I have your attention :)

I notice there are translated character templates in the repo. If I were to add more, should I add them "by hand", placing the new files amd adjusting the imports where needed, or are they added semiautomatically through some other process? The JSONs seems to have unique UUIDs for the sections, so I'm not certain how to proceed.

**Comment by RPDeshaies** [comment]
Hey! Thanks for opening this!

I just checked that you renamed a file from GL_es to GL. Why exactly did you do this ?

About your questions for character sheets, yeah there isn't a semi-automatic process (for now).
Like you mentioned, you gotta to add the JSON and update the imports and other places where it was used.

**Comment by xurxodiz** [comment]
(Thanks for the explanation. So how do I come up with the UUID for the JSON fields of the character sheets? I just improvise one and hope for no clashes?)

As for the file rename, I did it so it falls in line with how the other locales are named: fr, es, de… they have no country qualifier as they use a "generic" version of the language instead of being specifically fr_FR, es_MX, de_AT… with the notable exception of pt_BR because it's using specifically the brazilian variety and differences with pt_PT are notable.

**Comment by xurxodiz** [comment]
I noticed you changed the PR to merge against branch 5.1. I guess that branch adds new strings to be localized. Is there a place where can I see them already, to contribute them to this request? Otherwise I wait 🙂

**Comment by xurxodiz** [comment]
I reworked the branch for it to be rebased on `feat/v5.1.0`, but could not launch the app to check it works as that branch fails with an error on `yarn start`:

```
❯ yarn start
yarn run v1.22.10
$ vite --open
error when starting dev server:
Error: The following dependencies are imported but could not be resolved:

  @material-ui/core/styles/createMuiTheme (imported by [repo root]/lib/hooks/useThemeFromColor/useThemeFromColor.tsx)

Are they installed?
    at optimizeDeps ([repo root]/node_modules/vite/dist/node/chunks/dep-cc49d7be.js:72342:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOptimize ([repo root]/node_modules/vite/dist/node/chunks/dep-cc49d7be.js:73001:48)
    at async Server.httpServer.listen ([repo root]/node_modules/vite/dist/node/chunks/dep-cc49d7be.js:73015:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

(You most likely know this already, but just in case :) )

**Comment by RPDeshaies** [comment]
Yeah thats because v5.1 isn't using yarn anymore. I'll merge and double check. Thanks for this!!!

**Review by RPDeshaies — APPROVED** [review]

**Pull request merged**
